name: hs-io-exercise
version: '0.1.1'
synopsis: Haskell IO exercise
author: Maun Suang Boey <no-reply@example.com>
maintainer: Maun Suang Boey <no-reply@example.com>
copyright: © 2020 Maun Suang Boey, and Others
license: MIT
tested-with: GHC==8.8.2

ghc-options: -Wall -Wwarn -fwarn-tabs

dependencies:
  - base
  - bytestring
  - cassava
  - core-data
  - core-text
  - core-program >= 0.2.4
  - time
  - vector

executables:
  hello:
    source-dirs:
      - src
    main: IO-Exercise.hs
    ghc-options: -threaded

tests:
  check:
    dependencies:
      - hspec
    ghc-options: -threaded
    source-dirs:
      - tests
    main: TestSuite.hs
    other-modules: []
